#!/bin/bash
sed -i -e 's/\r$//' /usr/local/sbin/get-domain
sed -i -e 's/\r$//' /usr/local/sbin/get-backres
sed -i -e 's/\r$//' /usr/local/sbin/add-ssh
sed -i -e 's/\r$//' /usr/local/sbin/cek-ssh
sed -i -e 's/\r$//' /usr/local/sbin/renew-ssh
sed -i -e 's/\r$//' /usr/local/sbin/del-ssh
sed -i -e 's/\r$//' /usr/local/sbin/menu
sed -i -e 's/\r$//' /usr/local/sbin/ssh
sed -i -e 's/\r$//' /usr/local/sbin/vmess
sed -i -e 's/\r$//' /usr/local/sbin/vless
sed -i -e 's/\r$//' /usr/local/sbin/trojan
sed -i -e 's/\r$//' /usr/local/sbin/shadowsocks
sed -i -e 's/\r$//' /usr/local/sbin/run
sed -i -e 's/\r$//' /usr/local/sbin/seres
sed -i -e 's/\r$//' /usr/local/sbin/portin
sed -i -e 's/\r$//' /usr/local/sbin/xp
curl https://raw.githubusercontent.com/xxxserxxx/gotop/master/scripts/download.sh | bash && chmod +x gotop && sudo mv gotop /usr/local/sbin/
